name: Build ksud
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      os:
        required: false
        type: string
        default: ubuntu-latest
      pack_lkm:
        required: false
        type: boolean
        default: true
      pack_ksuinit:
        required: false
        type: boolean
        default: true
      use_cache:
        required: false
        type: boolean
        default: true
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build ksud (${{ inputs.target }})
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Prepare LKM fies
        if: ${{ inputs.pack_lkm }}
        run: |
          cp aarch64-android*-lkm/*_kernelsu.ko ./userspace/ksud/bin/aarch64/
          cp x86_64-android*-lkm/*_kernelsu.ko ./userspace/ksud/bin/x86_64/

      - name: Prepare ksuinit
        if: ${{ inputs.pack_ksuinit }}
        run: |
          mv ksuinit-aarch64/ksuinit ./userspace/ksud/bin/aarch64/
          mv ksuinit-x86_64/ksuinit ./userspace/ksud/bin/x86_64/

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          targets: ${{ inputs.target }}
          components: rust-src

      - uses: Swatinem/rust-cache@v2
        if: github.event_name != 'pull_request'
        with:
          prefix-key: ksud-${{ inputs.target }}
          workspaces: userspace/ksud
          cache-targets: true

      - name: Setup cargo-ndk
        run: cargo install cargo-ndk --locked

      - name: Assemble LKM bootstrap
        run: |
          clang --target=aarch64-linux-gnu -c -nostdlib \
            -o userspace/ksud/.lkm_image_bootstrap.o \
            userspace/ksud/src/lkm_image_bootstrap.S

      - name: Build ksud
        run: |
          if [ "${{github.event_name}}" == "pull_request" ]; then
            export KSU_PACKAGE_NAME="com.resukisu.resukisu.pr${{github.event.pull_request.number}}"
          elif [ "${{github.ref_type}}" != "tag" ] && [ "${{github.ref_name}}" != "main" ]; then
            export KSU_PACKAGE_NAME="com.resukisu.resukisu.dev"
          fi

          cd userspace/ksud/
          cargo ndk b -P 26 -t ${{ inputs.target }} -r -Z build-std-features="optimize_for_size" -Z trim-paths

      - name: Upload ksud artifact
        uses: actions/upload-artifact@v7
        with:
          name: ksud-${{ inputs.target }}
          path: userspace/ksud/target/**/release/ksud*
