name: Lints Check

on:
  push:
  pull_request:

permissions:
  checks: write

jobs:
  clang-format:
    name: ClangFormat check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Check
        working-directory: kernel
        run: make check-format

  rustfmt:
    name: Rustfmt check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - uses: LoliGothick/rustfmt-check@master
        with:
          token: ${{ github.token }}
          working-directory: userspace/ksud

      - uses: LoliGothick/rustfmt-check@master
        with:
          token: ${{ github.token }}
          working-directory: userspace/ksuinit

  clippy:
    name: Clippy check
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v7

      - run: |
          rustup update nightly
          rustup toolchain install nightly --component clippy
          rustup default nightly
          rustup target install aarch64-linux-android armv7-linux-androideabi x86_64-linux-android

      - uses: Swatinem/rust-cache@v2
        if: github.event_name != 'pull_request'
        with:
          workspaces: userspace/ksud

      - name: Setup cargo-ndk
        run: cargo install cargo-ndk --locked

      - name: Run Clippy
        run: |
          cd userspace/ksud
          cargo ndk -t arm64-v8a clippy
          cargo ndk -t x86_64 clippy
          cd ../ksuinit
          cargo ndk -t arm64-v8a clippy
          cargo ndk -t x86_64 clippy

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_names: gradlew
          ignore_paths: ./userspace/ksud/src/android/module/installer.sh ./.github/scripts/setup-rust-build.sh

  check-crlf:
    name: Check Line Endings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Regenerate Git Index based on .gitattributes
        run: |
          git config --global core.autocrlf false
          git rm --cached -r .
          git reset --hard HEAD

      - name: Verify no line ending conflicts
        run: |
          STATUS=$(git status --porcelain)
          if [ -n "$STATUS" ]; then
            exit 1
          fi

  android-lint:
    name: Check Manager Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./manager
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      
      - name: Check Manager Lint
        run: |
          ./gradlew lintDebug
