# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_EXYNOS) += \
	p3s_eur_openx_w01_r02.dtbo \
	p3s_eur_openx_w01_r16.dtbo \
	p3s_eur_openx_w01_r17.dtbo \
	p3s_eur_openx_w01_r18.dtbo \
	p3s_eur_openx_w01_r19.dtbo \
	p3s_eur_openx_w01_r20.dtbo \
	p3s_eur_openx_w01_r21.dtbo \
	p3s_eur_openx_w01_r22.dtbo
