name: Kernel Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name (example: v1.0)"
        required: true
      release_name:
        description: "Release name"
        required: true
        default: "Automated Kernel Build"
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - model: r9s
            branch: rebased-11
            variant: ksu
          - model: r9s
            branch: rebased-11
            variant: susfs
          - model: r9s
            branch: rebased-11
            variant: vanilla
    
          - model: o1s
            branch: rebased-11
            variant: ksu
          - model: o1s
            branch: rebased-11
            variant: susfs
          - model: o1s
            branch: rebased-11
            variant: vanilla
    
          - model: t2s
            branch: rebased-11
            variant: ksu
          - model: t2s
            branch: rebased-11
            variant: susfs
          - model: t2s
            branch: rebased-11
            variant: vanilla
    
          - model: p3s
            branch: rebased-11
            variant: ksu
          - model: p3s
            branch: rebased-11
            variant: susfs
          - model: p3s
            branch: rebased-11
            variant: vanilla
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ matrix.branch }}
        fetch-depth: 0
        submodules: recursive

    - name: Update apt
      run: sudo apt-get update

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          build-essential openjdk-8-jdk maven cmake byacc flex automake libtool-bin \
          bison binutils-dev libiberty-dev zip unzip libncurses5-dev curl git ninja-build \
          python3 libssl-dev gcc-aarch64-linux-gnu cpio gawk libarchive-tools lz4 repo

    - name: Set build flags for variant
      id: vars
      run: |
        if [ "${{ matrix.variant }}" = "ksu" ]; then
          echo "FLAGS=-k y" >> $GITHUB_OUTPUT
        elif [ "${{ matrix.variant }}" = "susfs" ]; then
          echo "FLAGS=-k y -s y" >> $GITHUB_OUTPUT
        else
          echo "FLAGS=" >> $GITHUB_OUTPUT
        fi

    - name: Run kernel build
      run: |
        chmod +x ./build.sh
        ./build.sh -m ${{ matrix.model }} ${{ steps.vars.outputs.FLAGS }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.model }}-${{ matrix.branch }}-${{ matrix.variant }}
        path: build/out/${{ matrix.model }}/*.zip


  release:
    needs: build
    runs-on: ubuntu-24.04

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        name: ${{ github.event.inputs.release_name || github.ref_name }}
        files: artifacts/**/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
