#
# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
#
# This program is free software and is provided to you under the terms of the
# GNU General Public License version 2 as published by the Free Software
# Foundation, and any use by you of this program is subject to the terms
# of such GNU licence.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, you can access it online at
# http://www.gnu.org/licenses/gpl-2.0.html.
#
# SPDX-License-Identifier: GPL-2.0
#

# Mali runtime version + redirect
# Mali runtime version chooser
obj-$(CONFIG_MALI_VERSION_SELECTOR) += mali_version_selector.o

# Compatibility stub: provides /sys/module/mali_kbase/ for userspace tools
obj-$(CONFIG_MALI_MIDGARD) += mali_kbase.o
mali_kbase-y := mali_kbase_compat.o

obj-$(CONFIG_MALI_MIDGARD_R38P0) += bv_r38p0/
obj-$(CONFIG_MALI_MIDGARD_R38P1) += v_r38p1/
obj-$(CONFIG_MALI_MIDGARD_R44P1) += v_r44p1/
obj-$(CONFIG_MALI_MIDGARD_R54P3) += v_r54p3/

obj-$(CONFIG_EXYNOS_GPEX) += exynos/
